name: Publish Docker image for tag

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Publish Docker image to nexus terrestris
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/') # Only run if the release is tagged
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          architecture: x64

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.ref }}
          labels: ${{ steps.meta.outputs.labels }}
